version: '3'
services:
  java-srv:
    build:
      context: java-srv
    ports:
      - "80:8080"
    depends_on:
      - db
    links:
      - "db:db"

  db:
    image: dolthub/dolt-sql-server
    ports:
      - 3306
    volumes:
      - ./db/sql:/docker-entrypoint-initdb.d
